name: ci

on:
  pull_request:
  workflow_dispatch:


jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node Environment
        uses: actions/setup-node@v4

      - name: Install Dependencies
        uses: npm ci

      - name: Build project
        uses: npm run build
